services:
  app:
    image: node:18-alpine
    command: sh -c "cd app && npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - docker.env

  mongo:
    image: mongo
    volumes:
      - mongo-data:/var/lib/mongodb
    env_file:
      - docker.env

volumes:
  mongo-data:

